# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  nginx:
    cap_add:
      - NET_BIND_SERVICE
    container_name: nginx
    environment:
      DISABLE_IPV6: true
    image: docker.io/jc21/nginx-proxy-manager:latest
    ports:
      - ${LOCAL_SERVER_IP}:81:81 # WebUI
      - 443:443 # Public HTTPS
      - 80:80 # Public HTTP
    restart: ${UNIVERSAL_RESTART_POLICY}
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - nginx-data:/data

volumes:
  letsencrypt-data:
  nginx-data: