# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  plex:
    container_name: plex
    devices:
      - /dev/dri:/dev/dri
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    image: lscr.io/linuxserver/plex:latest
    ports:
      - ${LOCAL_SERVER_IP}:32400:32400 # WebUI
      - ${LOCAL_SERVER_IP}:32410:32410/udp # GDM
      - ${LOCAL_SERVER_IP}:32412:32412/udp # GDM
      - ${LOCAL_SERVER_IP}:32413:32413/udp # GDM
      - ${LOCAL_SERVER_IP}:32414:32414/udp # GDM
      - ${LOCAL_SERVER_IP}:32469:32469 # DLNA
      - ${LOCAL_SERVER_IP}:5353:5353/udp # Bonjour/Avahi
      - ${LOCAL_SERVER_IP}:8324:8324 # Roku
    restart: ${UNIVERSAL_RESTART_POLICY}
    volumes:
      - ${MOVIE_DIR}:/movies:ro
      - ${TV_DIR}:/tv:ro
      - plex-config:/config