# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: ${UNIVERSAL_RESTART_POLICY}
    volumes:
      - ${COMPLETED_DOWNLOADS}:/downloads
      - qbittorrent-config:/config