# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  radarr:
    container_name: radarr
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - ${LOCAL_SERVER_IP}:7878:7878 # WebUI
    restart: ${UNIVERSAL_RESTART_POLICY}
    volumes:
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${MOVIE_DIR}:/movies
      - radarr-config:/config