# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: ${UNIVERSAL_RESTART_POLICY}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - radarr-config:/config
      - ${MOVIE_DIR}:/movies
      - ${COMPLETED_DOWNLOADS}:/downloads

volumes:
  radarr-config: