# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  registry:
    image: docker.io/registry:3
    container_name: registry
    restart: ${UNIVERSAL_RESTART_POLICY}