# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  socket:
    container_name: socket
    environment:
      AUTH: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1
      DELETE: 1
      DISTRIBUTION: 0
      EVENTS: 1
      EXEC: 0
      IMAGES: 1
      INFO: 1
      LOG_LEVEL: notice # debug, info, notice, warning, err, crit, alert, emerg
      NETWORKS: 1
      NODES: 0
      PING: 1
      PLUGINS: 0
      POST: 1
      SECRETS: 0
      SERVICES: 1
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1
      VERSION: 1
      VOLUMES: 1
    image: lscr.io/linuxserver/socket-proxy:latest
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    volumes:
      - /var/lib/haproxy/server-state:/var/lib/haproxy/server-state
      - ${SOCKET}:/var/run/docker.sock:ro