# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  sonarr:
    container_name: sonarr
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - ${LOCAL_SERVER_IP}:8989:8989 # WebUI
    restart: ${UNIVERSAL_RESTART_POLICY}
    volumes:
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${TV_DIR}:/tv
      - sonarr-config:/config