# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  watchtower:
    image: docker.io/containrrr/watchtower
    container_name: watchtower
    restart: always
    depends_on:
      - socket
    environment:
      DOCKER_HOST: tcp://socket:2375
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_SCHEDULE: 0 30 12 * * *
    security_opt:
      - no-new-privileges:true