# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: ${UNIVERSAL_RESTART_POLICY}
    depends_on:
      - socket
    ports:
      - "8443:443"
      - "2022:2022"
    tty: true
    environment:
      DOCKER_HOST: tcp://socket:2375
      TZ: ${TZ}
      WINGS_GID: ${PGID}
      WINGS_UID: ${PUID}
      WINGS_USERNAME: ${WINGS_USER}
    volumes:
      - "wings-config:/etc/pterodactyl"

volumes:
  wings-config: