# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-common-properties: &database
  MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE}
  MONGO_DBNAME: ${MONGO_DBNAME}
  MONGO_PASS: ${MONGO_PASS}
  MONGO_USER: ${MONGO_USER}

services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: ${UNIVERSAL_RESTART_POLICY}
    depends_on:
      - unifi-db
    ports:
      - ${PHYSICAL_SERVER_IP}:3478:3478/udp
      - ${PHYSICAL_SERVER_IP}:10001:10001/udp
      - ${PHYSICAL_SERVER_IP}:8080:8080
      - ${PHYSICAL_SERVER_IP}:1900:1900/udp
      - ${PHYSICAL_SERVER_IP}:6789:6789
      - ${PHYSICAL_SERVER_IP}:5514:5514/udp
    environment:
      <<: *database
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MONGO_HOST: unifi-db
      MONGO_PORT: 27017
    volumes:
      - unifi-data:/config

  unifi-db:
    image: docker.io/mongo:8.0-noble
    container_name: unifi-db
    restart: ${UNIVERSAL_RESTART_POLICY}
    environment:
      <<: *database
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:z

volumes:
  unifi-data:
  mongo-data: