# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: ${UNIVERSAL_RESTART_POLICY}
    ports:
      - ${PHYSICAL_SERVER_IP}:3478:3478/udp
      - ${PHYSICAL_SERVER_IP}:10001:10001/udp
      - ${PHYSICAL_SERVER_IP}:8080:8080
      - ${PHYSICAL_SERVER_IP}:1900:1900/udp
      - ${PHYSICAL_SERVER_IP}:6789:6789
      - ${PHYSICAL_SERVER_IP}:5514:5514/udp
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MONGO_USER:
      MONGO_PASS:
      MONGO_HOST:
      MONGO_PORT:
      MONGO_DBNAME:
      MONGO_AUTHSOURCE:
      MEM_LIMIT: 1024
      MEM_STARTUP: 1024
      MONGO_TLS:
    volumes:
      - unifi-data:/config

  unifi-db:
    image: docker.io/mongo:<version tag>
    container_name: unifi-db
    restart: ${UNIVERSAL_RESTART_POLICY}
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_USER:
      MONGO_PASS:
      MONGO_DBNAME:
      MONGO_AUTHSOURCE:
    volumes:
      - mongo-data:/data/db
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

volumes:
  unifi-data:
  mongo-data: